// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// f4
double f4(double x);
RcppExport SEXP testp_f4(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(f4(x));
    return __result;
END_RCPP
}
// f3
int f3(Rcpp::IntegerVector v1);
RcppExport SEXP testp_f3(SEXP v1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type v1(v1SEXP);
    __result = Rcpp::wrap(f3(v1));
    return __result;
END_RCPP
}
