# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f4 <- function(x) {
    .Call('C_testp_f4', PACKAGE = 'testp', x)
}

f3 <- function(v1) {
    .Call('C_testp_f3', PACKAGE = 'testp', v1)
}

